// 생성: 2026-10-07 22:53 KST

const CATEGORIES = [
  { id: "history", name: "한국사" },
  { id: "geography", name: "세계지리" },
  { id: "science", name: "과학" },
  { id: "culture", name: "예술과 문화" },
];

const QUESTIONS = {
  history: [
    {
      question: "아버지 광개토왕의 업적을 기리기 위해 광개토왕릉비를 세운 고구려의 왕은 누구인가?",
      choices: ["미천왕", "고국원왕", "장수왕", "소수림왕"],
      answer: 2,
      explanation: "광개토왕릉비는 414년 장수왕이 아버지 광개토왕의 업적을 기려 세운 비석이다.",
      source: "한국민족문화대백과사전, '광개토왕릉비'",
      url: "https://encykorea.aks.ac.kr/Article/E0005058",
    },
    {
      question: "372년 전진에서 승려 순도가 불상과 불경을 가져와 고구려에 불교가 전해졌을 때의 왕은 누구인가?",
      choices: ["소수림왕", "광개토왕", "장수왕", "고국천왕"],
      answer: 0,
      explanation: "고구려는 372년 소수림왕 때 전진의 순도를 통해 불교를 받아들였다.",
      source: "한국민족문화대백과사전, '불교'",
      url: "https://encykorea.aks.ac.kr/Article/E0024921",
    },
    {
      question: "698년 고구려 유민과 말갈인을 이끌고 동모산에서 발해를 세운 인물은 누구인가?",
      choices: ["궁예", "대조영", "견훤", "연개소문"],
      answer: 1,
      explanation: "발해는 698년 고구려 장수 출신 대조영이 동모산에서 세운 나라다.",
      source: "한국민족문화대백과사전, '발해'",
      url: "https://encykorea.aks.ac.kr/Article/E0021626",
    },
    {
      question: "고려 고종 때 새긴 팔만대장경판을 보관하고 있는 절은 어디인가?",
      choices: ["불국사", "송광사", "통도사", "해인사"],
      answer: 3,
      explanation: "팔만대장경판은 합천 해인사의 장경판전에 보관되어 있다.",
      source: "한국민족문화대백과사전, '합천 해인사 장경판전'",
      url: "https://encykorea.aks.ac.kr/Article/E0062725",
    },
    {
      question: "고려 광종이 958년 후주에서 귀화한 쌍기의 건의를 받아 처음 실시한 관리 선발 제도는 무엇인가?",
      choices: ["독서삼품과", "음서제", "과거제", "골품제"],
      answer: 2,
      explanation: "광종은 958년 쌍기의 건의에 따라 과거제를 처음 실시했다.",
      source: "한국민족문화대백과사전, '과거'",
      url: "https://encykorea.aks.ac.kr/Article/E0004562",
    },
    {
      question: "1443년 훈민정음을 창제한 조선의 왕은 누구인가?",
      choices: ["세종", "태종", "세조", "성종"],
      answer: 0,
      explanation: "세종은 1443년 훈민정음을 창제하고 1446년 책으로 펴내 반포했다.",
      source: "한국민족문화대백과사전, '훈민정음'",
      url: "https://encykorea.aks.ac.kr/Article/E0065805",
    },
    {
      question: "1592년 한산도 앞바다에서 학익진을 펼쳐 일본 수군을 크게 무찌른 조선의 장수는 누구인가?",
      choices: ["권율", "김시민", "곽재우", "이순신"],
      answer: 3,
      explanation: "이순신은 1592년 한산도대첩에서 학익진으로 일본 수군의 주력을 격파했다.",
      source: "한국민족문화대백과사전, '한산도대첩'",
      url: "https://encykorea.aks.ac.kr/Article/E0061676",
    },
    {
      question: "수령이 지켜야 할 도리와 지방 통치 방법을 담은 『목민심서』를 지은 조선 후기 실학자는 누구인가?",
      choices: ["박지원", "정약용", "유형원", "이익"],
      answer: 1,
      explanation: "『목민심서』는 정약용이 강진 유배 중에 써서 1818년에 완성한 책이다.",
      source: "한국민족문화대백과사전, '목민심서'",
      url: "https://encykorea.aks.ac.kr/Article/E0018631",
    },
    {
      question: "민족 대표 33인이 독립선언서를 발표하며 3·1 운동이 시작된 해는 언제인가?",
      choices: ["1910년", "1919년", "1926년", "1945년"],
      answer: 1,
      explanation: "3·1 운동은 1919년 3월 1일 독립선언서 발표와 함께 시작되었다.",
      source: "한국민족문화대백과사전, '3·1독립선언서'",
      url: "https://encykorea.aks.ac.kr/Article/E0026764",
    },
    {
      question: "1919년 4월 11일 대한민국 임시 정부가 수립된 도시는 어디인가?",
      choices: ["충칭", "블라디보스토크", "상하이", "베이징"],
      answer: 2,
      explanation: "대한민국 임시 정부는 1919년 4월 11일 중국 상하이에서 수립되었다.",
      source: "한국민족문화대백과사전, '대한민국 임시정부'",
      url: "https://encykorea.aks.ac.kr/Article/E0015017",
    },
    {
      question: "아버지 사도세자의 무덤을 수원으로 옮긴 뒤 수원 화성을 쌓게 한 조선의 왕은 누구인가?",
      choices: ["영조", "숙종", "순조", "정조"],
      answer: 3,
      explanation: "수원 화성은 정조가 아버지 사도세자의 무덤을 수원으로 옮긴 뒤 쌓은 성곽이다.",
      source: "한국민족문화대백과사전, '수원 화성'",
      url: "https://encykorea.aks.ac.kr/Article/E0064671",
    },
    {
      question: "918년 궁예를 몰아내고 고려를 세운 인물은 누구인가?",
      choices: ["왕건", "견훤", "신검", "최승로"],
      answer: 0,
      explanation: "왕건은 918년 궁예를 몰아내고 왕위에 올라 나라 이름을 고려라고 했다.",
      source: "한국민족문화대백과사전, '태조'",
      url: "https://encykorea.aks.ac.kr/Article/E0059032",
    },
  ],
  geography: [
    {
      question: "오스트레일리아의 수도는 어디인가?",
      choices: ["시드니", "멜버른", "캔버라", "퍼스"],
      answer: 2,
      explanation: "오스트레일리아의 수도는 1927년부터 공식 수도가 된 캔버라다.",
      source: "브리태니커, 'What is the capital of Australia?'",
      url: "https://www.britannica.com/question/What-is-the-capital-of-Australia",
    },
    {
      question: "안데스산맥이 남북으로 길게 뻗어 있는 대륙은 어디인가?",
      choices: ["남아메리카", "아프리카", "유럽", "오세아니아"],
      answer: 0,
      explanation: "안데스산맥은 남아메리카 대륙의 서쪽을 따라 남북으로 뻗어 있다.",
      source: "브리태니커, 'Andes Mountains'",
      url: "https://www.britannica.com/place/Andes-Mountains",
    },
    {
      question: "(2024년 기준, 국토 면적 기준) 세계에서 가장 넓은 나라는 어디인가?",
      choices: ["캐나다", "러시아", "중국", "미국"],
      answer: 1,
      explanation: "러시아는 약 1,708만 제곱킬로미터로 두 번째인 캐나다의 두 배 가까운 면적을 가진 나라다.",
      source: "브리태니커, 'List of the world’s largest countries and dependencies by area'",
      url: "https://www.britannica.com/topic/list-of-the-total-areas-of-the-worlds-countries-dependencies-and-territories-2130540",
    },
    {
      question: "독일에서 시작해 여러 나라를 지나 흐르는 다뉴브강(도나우강)이 흘러드는 바다는 어디인가?",
      choices: ["북해", "지중해", "발트해", "흑해"],
      answer: 3,
      explanation: "다뉴브강은 독일 남서부에서 시작해 9개 나라를 지나 흑해로 흘러든다.",
      source: "브리태니커, 'Danube River'",
      url: "https://www.britannica.com/place/Danube-River",
    },
    {
      question: "에베레스트산이 속한 산맥은 어디인가?",
      choices: ["알프스산맥", "히말라야산맥", "안데스산맥", "로키산맥"],
      answer: 1,
      explanation: "에베레스트산은 네팔과 중국 티베트 자치구의 경계에 있는 히말라야산맥의 산이다.",
      source: "브리태니커, 'Mount Everest'",
      url: "https://www.britannica.com/place/Mount-Everest",
    },
    {
      question: "남아메리카에 있는 브라질의 공용어는 무엇인가?",
      choices: ["스페인어", "영어", "프랑스어", "포르투갈어"],
      answer: 3,
      explanation: "브라질은 16세기 포르투갈의 식민지가 된 영향으로 포르투갈어를 공용어로 쓴다.",
      source: "브리태니커, 'Portuguese language'",
      url: "https://www.britannica.com/topic/Portuguese-language",
    },
    {
      question: "적도 부근에 나타나며 1년 내내 기온이 높고 비가 많이 내리는 기후는 무엇인가?",
      choices: ["열대 우림 기후", "사막 기후", "지중해성 기후", "툰드라 기후"],
      answer: 0,
      explanation: "열대 우림 기후는 적도 부근에서 1년 내내 덥고 강수량이 많은 기후다.",
      source: "브리태니커, 'Wet equatorial climate'",
      url: "https://www.britannica.com/science/wet-equatorial-climate",
    },
    {
      question: "피레네산맥을 경계로 국경을 맞대고 있는 두 나라는 어디인가?",
      choices: ["스페인과 포르투갈", "프랑스와 이탈리아", "프랑스와 스페인", "독일과 폴란드"],
      answer: 2,
      explanation: "피레네산맥의 능선은 대부분 프랑스와 스페인의 국경을 이룬다.",
      source: "브리태니커, 'Pyrenees'",
      url: "https://www.britannica.com/place/Pyrenees",
    },
    {
      question: "이집트의 수에즈 운하가 연결하는 두 바다는 어디인가?",
      choices: ["지중해와 홍해", "대서양과 태평양", "흑해와 지중해", "홍해와 아라비아해"],
      answer: 0,
      explanation: "1869년에 완공된 수에즈 운하는 지중해와 홍해를 잇는다.",
      source: "브리태니커, 'Suez Canal'",
      url: "https://www.britannica.com/topic/Suez-Canal",
    },
    {
      question: "(해발 고도 기준) 일본에서 가장 높은 산은 무엇인가?",
      choices: ["아소산", "다테야마", "후지산", "기타다케"],
      answer: 2,
      explanation: "후지산은 높이 3,776미터로 일본에서 가장 높은 산이다.",
      source: "브리태니커, 'Mount Fuji'",
      url: "https://www.britannica.com/place/Mount-Fuji",
    },
    {
      question: "튀르키예의 수도는 어디인가?",
      choices: ["이스탄불", "앙카라", "이즈미르", "안탈리아"],
      answer: 1,
      explanation: "튀르키예의 수도는 이스탄불이 아니라 앙카라다.",
      source: "브리태니커, 'Ankara'",
      url: "https://www.britannica.com/place/Ankara",
    },
    {
      question: "아마존강이 흘러드는 대양은 어디인가?",
      choices: ["태평양", "인도양", "북극해", "대서양"],
      answer: 3,
      explanation: "아마존강은 브라질을 지나 대서양으로 흘러든다.",
      source: "브리태니커, 'Amazon River'",
      url: "https://www.britannica.com/place/Amazon-River",
    },
  ],
  science: [
    {
      question: "국제단위계(SI)에서 힘의 단위는 무엇인가?",
      choices: ["줄", "뉴턴", "와트", "파스칼"],
      answer: 1,
      explanation: "1뉴턴은 질량 1킬로그램인 물체에 1m/s²의 가속도를 내는 힘이다.",
      source: "브리태니커, 'newton'",
      url: "https://www.britannica.com/science/newton-unit-of-measurement",
    },
    {
      question: "외부에서 힘이 작용하지 않으면 정지한 물체는 계속 정지하고, 움직이는 물체는 같은 속도로 직선 운동을 계속한다는 법칙은 무엇인가?",
      choices: ["가속도의 법칙", "작용 반작용의 법칙", "관성의 법칙", "만유인력의 법칙"],
      answer: 2,
      explanation: "뉴턴의 운동 제1법칙을 관성의 법칙이라고 한다.",
      source: "브리태니커, 'Newton’s laws of motion'",
      url: "https://www.britannica.com/science/Newtons-laws-of-motion",
    },
    {
      question: "원소 기호 Fe가 나타내는 원소는 무엇인가?",
      choices: ["불소", "철", "납", "구리"],
      answer: 1,
      explanation: "Fe는 철을 뜻하는 라틴어 ferrum에서 온 원소 기호다.",
      source: "브리태니커, 'Why is the chemical symbol for iron Fe?'",
      url: "https://www.britannica.com/science/Why-is-the-chemical-symbol-for-iron-Fe",
    },
    {
      question: "(건조한 공기의 부피 비율 기준) 지구 대기에 가장 많이 들어 있는 기체는 무엇인가?",
      choices: ["산소", "아르곤", "이산화 탄소", "질소"],
      answer: 3,
      explanation: "건조한 공기의 약 78퍼센트는 질소이고, 산소는 약 21퍼센트다.",
      source: "브리태니커, 'nitrogen'",
      url: "https://www.britannica.com/science/nitrogen",
    },
    {
      question: "25°C에서 순수한 물의 pH는 얼마인가?",
      choices: ["0", "4", "7", "14"],
      answer: 2,
      explanation: "25°C의 순수한 물은 중성이며 pH는 7이다.",
      source: "브리태니커 학생용, 'pH'",
      url: "https://kids.britannica.com/students/article/pH/332990",
    },
    {
      question: "식물 세포에서 광합성이 일어나는 세포 소기관은 무엇인가?",
      choices: ["엽록체", "미토콘드리아", "리보솜", "핵"],
      answer: 0,
      explanation: "엽록체는 엽록소로 빛에너지를 흡수해 광합성을 하는 세포 소기관이다.",
      source: "브리태니커, 'What is a chloroplast?'",
      url: "https://www.britannica.com/question/What-is-a-chloroplast",
    },
    {
      question: "사람의 적혈구 속에서 산소를 온몸의 조직으로 운반하는 단백질은 무엇인가?",
      choices: ["인슐린", "케라틴", "아밀레이스", "헤모글로빈"],
      answer: 3,
      explanation: "헤모글로빈은 철을 포함한 단백질로, 폐에서 산소와 결합해 조직으로 운반한다.",
      source: "브리태니커, 'Blood - Red blood cells (erythrocytes)'",
      url: "https://www.britannica.com/science/blood-biochemistry/Red-blood-cells-erythrocytes",
    },
    {
      question: "1953년 DNA의 이중 나선 구조를 밝혀 발표한 두 과학자는 누구인가?",
      choices: ["왓슨과 크릭", "멘델과 모건", "다윈과 월리스", "파스퇴르와 코흐"],
      answer: 0,
      explanation: "제임스 왓슨과 프랜시스 크릭은 1953년 DNA가 이중 나선 구조라는 모형을 발표했다.",
      source: "브리태니커, 'Double helix'",
      url: "https://www.britannica.com/science/double-helix",
    },
    {
      question: "(질량 기준) 태양계에서 가장 큰 행성은 무엇인가?",
      choices: ["토성", "목성", "천왕성", "해왕성"],
      answer: 1,
      explanation: "목성의 질량은 지구의 약 318배로, 나머지 행성을 모두 합친 것보다 크다.",
      source: "브리태니커, 'Jupiter'",
      url: "https://www.britannica.com/place/Jupiter-planet",
    },
    {
      question: "태양의 자외선을 흡수하는 오존층은 대기의 어느 층에 있는가?",
      choices: ["성층권", "대류권", "중간권", "열권"],
      answer: 0,
      explanation: "오존층은 지상 약 15~35킬로미터 높이의 성층권에 있다.",
      source: "브리태니커 학생용, 'ozone'",
      url: "https://kids.britannica.com/students/article/ozone/609444",
    },
    {
      question: "원자 번호가 1인 원소는 무엇인가?",
      choices: ["헬륨", "산소", "수소", "탄소"],
      answer: 2,
      explanation: "수소는 원자 번호가 1인 원소이며 원소 기호는 H다.",
      source: "브리태니커, 'hydrogen'",
      url: "https://www.britannica.com/science/hydrogen",
    },
    {
      question: "식탁에서 쓰는 소금의 주성분인 화합물은 무엇인가?",
      choices: ["탄산 칼슘", "수산화 나트륨", "염화 칼륨", "염화 나트륨"],
      answer: 3,
      explanation: "식탁용 소금의 화학 이름은 염화 나트륨(NaCl)이다.",
      source: "브리태니커, 'salt'",
      url: "https://www.britannica.com/science/salt",
    },
  ],
  culture: [
    {
      question: "프랑스 루브르 박물관에 있는 「모나리자」를 그린 화가는 누구인가?",
      choices: ["미켈란젤로", "라파엘로", "보티첼리", "레오나르도 다빈치"],
      answer: 3,
      explanation: "「모나리자」는 레오나르도 다빈치가 1503년 무렵부터 그린 유화 초상화다.",
      source: "브리태니커, 'Leonardo da Vinci'",
      url: "https://www.britannica.com/biography/Leonardo-da-Vinci",
    },
    {
      question: "마지막 악장에서 합창이 실러의 시 「환희의 송가」를 부르는 교향곡 9번 「합창」을 작곡한 사람은 누구인가?",
      choices: ["모차르트", "베토벤", "바흐", "하이든"],
      answer: 1,
      explanation: "교향곡 9번은 1824년 빈에서 초연된 베토벤의 마지막 교향곡이다.",
      source: "브리태니커, 'Symphony No. 9 in D Minor, Op. 125'",
      url: "https://www.britannica.com/topic/Symphony-No-9-in-D-Minor",
    },
    {
      question: "1871년 이집트 카이로에서 초연된 오페라 「아이다」를 작곡한 사람은 누구인가?",
      choices: ["푸치니", "바그너", "베르디", "로시니"],
      answer: 2,
      explanation: "「아이다」는 이탈리아 작곡가 주세페 베르디가 이집트의 의뢰를 받아 작곡한 오페라다.",
      source: "브리태니커, 'Giuseppe Verdi - The later middle years'",
      url: "https://www.britannica.com/biography/Giuseppe-Verdi/The-later-middle-years",
    },
    {
      question: "덴마크 왕자가 아버지의 죽음에 복수하려는 이야기를 담은 비극 「햄릿」을 쓴 작가는 누구인가?",
      choices: ["셰익스피어", "괴테", "세르반테스", "단테"],
      answer: 0,
      explanation: "「햄릿」은 윌리엄 셰익스피어가 1599~1601년 무렵에 쓴 5막 비극이다.",
      source: "브리태니커, 'Hamlet'",
      url: "https://www.britannica.com/topic/Hamlet-by-Shakespeare",
    },
    {
      question: "\"나 보기가 역겨워 가실 때에는\"으로 시작하는 시 「진달래꽃」을 쓴 시인은 누구인가?",
      choices: ["윤동주", "김소월", "한용운", "이육사"],
      answer: 1,
      explanation: "「진달래꽃」은 김소월이 1922년 『개벽』에 처음 발표한 시다.",
      source: "한국민족문화대백과사전, '진달래꽃'",
      url: "https://encykorea.aks.ac.kr/Article/E0054623",
    },
    {
      question: "스페인 바르셀로나의 사그라다 파밀리아 성당 건축을 1883년부터 맡아 이끈 건축가는 누구인가?",
      choices: ["르코르뷔지에", "프랭크 로이드 라이트", "안토니 가우디", "미스 반데어로에"],
      answer: 2,
      explanation: "안토니 가우디는 1883년 사그라다 파밀리아의 책임 건축가가 되어 성당을 독창적인 건축물로 바꾸었다.",
      source: "브리태니커, 'Sagrada Família'",
      url: "https://www.britannica.com/topic/Sagrada-Familia",
    },
    {
      question: "판소리에서 소리꾼 옆에 앉아 북으로 장단을 치고 추임새를 넣는 사람을 무엇이라고 하는가?",
      choices: ["고수", "명창", "재인", "악공"],
      answer: 0,
      explanation: "고수는 판소리에서 소리북으로 장단을 치며 소리판의 분위기를 이끄는 사람이다.",
      source: "한국민족문화대백과사전, '고수'",
      url: "https://encykorea.aks.ac.kr/Article/E0003767",
    },
    {
      question: "제주도 유배 중이던 1844년 제자 이상적에게 그려 준 「세한도」의 작가는 누구인가?",
      choices: ["김홍도", "신윤복", "정선", "김정희"],
      answer: 3,
      explanation: "「세한도」는 김정희가 제주 유배 중 제자 이상적의 의리에 답례로 그린 그림이다.",
      source: "한국민족문화대백과사전, '김정희 필 세한도'",
      url: "https://encykorea.aks.ac.kr/Article/E0038956",
    },
    {
      question: "캄보디아의 세계유산 앙코르 유적을 대표하는 크메르 왕국의 사원은 무엇인가?",
      choices: ["앙코르와트", "보로부두르", "타지마할", "페트라"],
      answer: 0,
      explanation: "앙코르와트는 9~15세기 크메르 왕국의 수도 유적인 앙코르를 대표하는 사원이다.",
      source: "유네스코 세계유산센터, 'Angkor'",
      url: "https://whc.unesco.org/en/list/668/",
    },
    {
      question: "1889년 프랑스 생레미의 요양원에 머물며 「별이 빛나는 밤」을 그린 화가는 누구인가?",
      choices: ["모네", "빈센트 반 고흐", "고갱", "세잔"],
      answer: 1,
      explanation: "「별이 빛나는 밤」은 빈센트 반 고흐가 1889년 생레미의 요양원에서 그린 그림이다.",
      source: "뉴욕 현대 미술관(MoMA), 'Vincent van Gogh. The Starry Night'",
      url: "https://www.moma.org/collection/works/79802",
    },
    {
      question: "봄, 여름, 가을, 겨울을 각각 음악으로 그린 바이올린 협주곡 4곡 「사계」를 작곡한 사람은 누구인가?",
      choices: ["바흐", "헨델", "텔레만", "비발디"],
      answer: 3,
      explanation: "「사계」는 안토니오 비발디가 쓴 바이올린 협주곡 4곡으로, 1725년 출판된 협주곡집에 실렸다.",
      source: "브리태니커, 'The Four Seasons'",
      url: "https://www.britannica.com/topic/The-Four-Seasons-by-Vivaldi",
    },
    {
      question: "1877년 처음 무대에 오른 발레 「백조의 호수」의 음악을 작곡한 사람은 누구인가?",
      choices: ["라흐마니노프", "무소륵스키", "차이콥스키", "스트라빈스키"],
      answer: 2,
      explanation: "「백조의 호수」는 차이콥스키가 처음으로 작곡한 발레 음악으로, 1877년에 초연되었다.",
      source: "브리태니커, 'Swan Lake'",
      url: "https://www.britannica.com/topic/Swan-Lake-ballet-by-Tchaikovsky",
    },
  ],
};
